name: Playwright Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    # Cache npm modules
    - name: Cache node modules
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    # Cache Playwright browsers
    - name: Cache Playwright browsers
      uses: actions/cache@v3
      with:
        path: ~/.cache/ms-playwright
        key: ${{ runner.os }}-playwright-browsers

    - uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Run Playwright tests
      run: npx playwright test

    - name: Upload Playwright HTML report
      uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30

    - name: Upload JUnit test results
      uses: actions/upload-artifact@v4
      if: ${{ always() }}
      with:
        name: junit-results
        path: test-results/results.xml

    - name: Add test summary to GitHub Actions UI
      if: always()
      run: |
        echo "## ✅ Playwright Test Summary" >> $GITHUB_STEP_SUMMARY
        echo "Test run completed on branch: \`${{ github.ref_name }}\`" >> $GITHUB_STEP_SUMMARY
        echo "🎯 View the full HTML report in the Artifacts section below." >> $GITHUB_STEP_SUMMARY

    - name: Install datadog-ci CLI
      run: npm install -g @datadog/datadog-ci

    - name: Send metrics to Datadog
      env:
        DD_API_KEY: ${{ secrets.DATADOG_API_KEY }}
        DD_SITE: datadoghq.eu
      run: |
        datadog-ci tests run --reporter junit --files test-results/results.xml